"""add cart tables

Revision ID: 33daba0ac7bd
Revises: 5e1452586ca0
Create Date: 2026-05-07 14:43:10.783108
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.core.config import get_settings


# revision identifiers, used by Alembic.
revision = '33daba0ac7bd'
down_revision = '5e1452586ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    settings = get_settings()
    schema = None if settings.database_url.startswith("sqlite") else settings.database_schema

    def fk(table_name: str, column: str = "id") -> str:
        return f"{schema}.{table_name}.{column}" if schema else f"{table_name}.{column}"

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [fk("users")], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('ix_carts_status', 'carts', ['status'], unique=False, schema=schema)
    op.create_index('ix_carts_user_id', 'carts', ['user_id'], unique=False, schema=schema)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], [fk("carts")], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], [fk("product_variants")], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_variant_id', name='uq_cart_items_cart_variant'),
    schema=schema
    )
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False, schema=schema)
    op.create_index('ix_cart_items_product_variant_id', 'cart_items', ['product_variant_id'], unique=False, schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    settings = get_settings()
    schema = None if settings.database_url.startswith("sqlite") else settings.database_schema

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_items_product_variant_id', table_name='cart_items', schema=schema)
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items', schema=schema)
    op.drop_table('cart_items', schema=schema)
    op.drop_index('ix_carts_user_id', table_name='carts', schema=schema)
    op.drop_index('ix_carts_status', table_name='carts', schema=schema)
    op.drop_table('carts', schema=schema)
    # ### end Alembic commands ###
