"""add catalog tables

Revision ID: 5e1452586ca0
Revises: 20260507_0001
Create Date: 2026-05-07 12:22:43.564996
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.core.config import get_settings


# revision identifiers, used by Alembic.
revision = '5e1452586ca0'
down_revision = '20260507_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    settings = get_settings()
    schema = None if settings.database_url.startswith("sqlite") else settings.database_schema

    def fk(table_name: str, column: str = "id") -> str:
        return f"{schema}.{table_name}.{column}" if schema else f"{table_name}.{column}"

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_brands_slug'),
    schema=schema
    )
    op.create_index('ix_brands_name', 'brands', ['name'], unique=False, schema=schema)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], [fk('categories')], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_categories_slug'),
    schema=schema
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False, schema=schema)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], [fk('brands')], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], [fk('categories')], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_products_slug'),
    schema=schema
    )
    op.create_index('ix_products_brand_id', 'products', ['brand_id'], unique=False, schema=schema)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False, schema=schema)
    op.create_index('ix_products_name', 'products', ['name'], unique=False, schema=schema)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], [fk('products')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False, schema=schema)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], [fk('products')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_product_variants_sku'),
    schema=schema
    )
    op.create_index('ix_product_variants_product_id', 'product_variants', ['product_id'], unique=False, schema=schema)
    op.create_index('ix_product_variants_sku', 'product_variants', ['sku'], unique=False, schema=schema)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reorder_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], [fk('product_variants')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', name='uq_inventory_variant_id'),
    schema=schema
    )
    op.create_index('ix_inventory_variant_id', 'inventory', ['variant_id'], unique=False, schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    settings = get_settings()
    schema = None if settings.database_url.startswith("sqlite") else settings.database_schema

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_variant_id', table_name='inventory', schema=schema)
    op.drop_table('inventory', schema=schema)
    op.drop_index('ix_product_variants_sku', table_name='product_variants', schema=schema)
    op.drop_index('ix_product_variants_product_id', table_name='product_variants', schema=schema)
    op.drop_table('product_variants', schema=schema)
    op.drop_index('ix_product_images_product_id', table_name='product_images', schema=schema)
    op.drop_table('product_images', schema=schema)
    op.drop_index('ix_products_name', table_name='products', schema=schema)
    op.drop_index('ix_products_category_id', table_name='products', schema=schema)
    op.drop_index('ix_products_brand_id', table_name='products', schema=schema)
    op.drop_table('products', schema=schema)
    op.drop_index('ix_categories_name', table_name='categories', schema=schema)
    op.drop_table('categories', schema=schema)
    op.drop_index('ix_brands_name', table_name='brands', schema=schema)
    op.drop_table('brands', schema=schema)
    # ### end Alembic commands ###
