"""add order tables

Revision ID: 939944e00b75
Revises: 33daba0ac7bd
Create Date: 2026-05-07 15:57:22.132370
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.core.config import get_settings


# revision identifiers, used by Alembic.
revision = '939944e00b75'
down_revision = '33daba0ac7bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    settings = get_settings()
    schema = None if settings.database_url.startswith("sqlite") else settings.database_schema

    def fk(table_name: str, column: str = "id") -> str:
        return f"{schema}.{table_name}.{column}" if schema else f"{table_name}.{column}"

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [fk("users")], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False, schema=schema)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False, schema=schema)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], [fk("users")], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], [fk("orders")], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('ix_order_status_history_order_id', 'order_status_history', ['order_id'], unique=False, schema=schema)
    op.create_index('ix_order_status_history_to_status', 'order_status_history', ['to_status'], unique=False, schema=schema)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], [fk("orders")], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], [fk("product_variants")], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False, schema=schema)
    op.create_index('ix_order_items_product_variant_id', 'order_items', ['product_variant_id'], unique=False, schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    settings = get_settings()
    schema = None if settings.database_url.startswith("sqlite") else settings.database_schema

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_product_variant_id', table_name='order_items', schema=schema)
    op.drop_index('ix_order_items_order_id', table_name='order_items', schema=schema)
    op.drop_table('order_items', schema=schema)
    op.drop_index('ix_order_status_history_to_status', table_name='order_status_history', schema=schema)
    op.drop_index('ix_order_status_history_order_id', table_name='order_status_history', schema=schema)
    op.drop_table('order_status_history', schema=schema)
    op.drop_index('ix_orders_user_id', table_name='orders', schema=schema)
    op.drop_index('ix_orders_status', table_name='orders', schema=schema)
    op.drop_table('orders', schema=schema)
    # ### end Alembic commands ###
